name: luarsekolah_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.3.2
  shared_preferences: ^2.2.3
  image_picker: ^1.0.4
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  lottie: ^3.1.0
  dio: ^5.4.3
  animations: ^2.0.7
  get: ^4.6.6     # State management
  dartz: ^0.10.1       # Functional programming (Either)
  equatable: ^2.0.5    # Value equality
  firebase_core: ^3.15.2
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.6.12
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^19.5.0
  permission_handler: ^11.3.1
  timezone: ^0.10.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/lottie/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/ls-icon.png"
  
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/ls-icon.png"